services:
  cra-farewell:
    build: 
      context: .
    ports:
      - "3030:3000"
    networks:
      app_net:
        ipv4_address: 192.168.3.100
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: "1024M"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
